services:
  app:
    container_name: app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - ${PORT}:${PORT}
    networks:
      - app-db
    depends_on:
      - db
    env_file:
      - .env
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /usr/app/src
  db:
    container_name: db
    restart: on-failure
    shm_size: 32mb
    volumes:
      - db-data:/var/libs/postgresql/data
      - db-logs:/var/log/postgresql
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - app-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PSWD}
      POSTGRES_DB: ${DB}
    env_file:
      - .env

networks:
  app-db: {}

volumes:
  db-data:
  db-logs:
